(defparameter *winning-lines*
  '((0 1 2) (3 4 5) (6 7 8)
    (0 3 6) (1 4 7) (2 5 8)
    (0 4 8) (2 4 6)))
(defun empty-board ()
  (make-list 9 :initial-element nil))
(defun switch-player (p)
  (if (eq p 'X) 'O 'X))
(defun winner (board)
  (dolist (line *winning-lines*)
    (let ((a (nth (first line) board))
          (b (nth (second line) board))
          (c (nth (third line) board)))
      (when (and a (eq a b) (eq b c))
        (return a)))))
(defun terminal-state-p (board)
  (or (winner board)
      (not (member nil board))))
(defun successors (board player)
  (loop for i from 0 to 8
        when (null (nth i board))
        collect
        (let ((new-board (copy-list board)))
          (setf (nth i new-board) player)
          (list new-board (switch-player player)))))
(defun bfs-tic-tac-toe ()
  (let ((queue (list (list (empty-board) 'X))))
    (loop while queue do
      (let* ((state (pop queue))
             (board (first state))
             (player (second state)))
        (when (terminal-state-p board)
          (return (winner board)))
        (setf queue
              (append queue (successors board player)))))))
(format t "Result: ~A~%" (bfs-tic-tac-toe))
