(defparameter *cities* '(A B C D))
(defparameter *dist*
  '((0 10 15 20)
    (10 0 35 25)
    (15 35 0 30)
    (20 25 30 0)))
(defun index-of (city)
  (position city *cities*))
(defun distance (c1 c2)
  (nth (index-of c2)
       (nth (index-of c1) *dist*)))
(defun nearest-city (current unvisited)
  (car
   (sort unvisited #'<
         :key (lambda (c)
                (distance current c)))))
(defun tsp-heuristic (start)
  (let ((current start)
        (unvisited (remove start *cities*))
        (path (list start))
        (cost 0))
    (loop while unvisited do
      (let ((next (nearest-city current unvisited)))
        (incf cost (distance current next))
        (push next path)
        (setf current next)
        (setf unvisited (remove next unvisited))))
    (incf cost (distance current start))
    (push start path)
    (format t "~%Path: ~a" (reverse path))
    (format t "~%Total Cost: ~a" cost)))
(tsp-heuristic 'A)
