(defparameter *visited* nil )
(defun goal-p (state)
  (=(first state)2))
(defun successors (state)
(let ((a (first state))
      (b (second state)))
      (remove-duplicates
      (list
      (list 4 b )
      (list a 3)
      (list 0 b )
      (list a 0)
      (list (- a (min a(- 3 b)))
            (+ b (min a(- 3 b))))
      (list (+ a (min b(- 4 a)))
            (- b (min b(- 4 a)))))
      :test #'equal)))
(defun dfs (state)
  (cond 
    ((goal-p state)
    (format t "~%Goal Reached : ~a" state)
    t)
    ((member state *visited* :test #'equal)
    nil)
    (t
      (push state *visited*)
      (dolist (next (successors state))
      (when (dfs next)
        (format t "~%~a" state)
        (return t))))))
(defun solve()
  (setf *visited* nil)
  (dfs '(0 0)))
(solve)
